_BASE_: ../maskformer2_R50_bs16_300k.yaml
MODEL:
  BACKBONE:
    NAME: "D2DinoVisionTransformer"
  WEIGHTS: "model_weights/dinov2_converted_1024x1024_p16_backbone.pth"
  MASK_FORMER:
    DEC_LAYERS: 2
    OUTLIER_SUPERVISION: True
    OUTLIER_LOSS_TARGET: "nls"
    NUM_OBJECT_QUERIES: 100
  SEM_SEG_HEAD:
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res5"]
    IGNORE_VALUE: 255
    NUM_CLASSES: 2
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  FREEZE_PIXEL_DECODER: False
  FREEZE_BACKBONE: True
  FREEZE_TRANSFORMER_DECODER_EXCEPT_MLP: False
DATASETS:
  TRAIN: ("mapillary_cityscapes_sem_seg_train", "cityscapes_fine_sem_seg_train")
  TEST: ("mapillary_cityscapes_sem_seg_val",)
INPUT:
  MIN_SIZE_TRAIN: !!python/object/apply:eval ["[int(x * 0.1 * 2048) for x in range(5, 7)]"]
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 2048
  MAX_SIZE_TRAIN: 8192
  MAX_SIZE_TEST: 2048
  CROP:
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  DATASET_MAPPER_NAME: "mask_former_semantic_coco_mix_binary"
  SIZE_DIVISIBILITY: -1
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  CHECKPOINT_PERIOD: 10000
  IMS_PER_BATCH: 16 #* Important
  BASE_LR: 0.0001
  MAX_ITER: 90000
TEST:
  EVAL_PERIOD: 100000
OUTPUT_DIR: './results/Rba_dinov2_binary'